<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    
    <!-- NuGet Package Metadata -->
    <PackageId>Errgo</PackageId>
    <Version>0.1.0</Version>
    <Authors>Diego Rönkkömäki-Tapia</Authors>
    <Description>Errors-as-values in C#</Description>
    <PackageTags>error-handling;go;errors;result</PackageTags>
    <PackageProjectUrl>https://github.com/TDMR87/Errgo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TDMR87/Errgo</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    
    <!-- Include analyzers in package -->
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>

</Project>
