<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <WarningsAsErrors>nullable</WarningsAsErrors>
    
    <!-- NuGet Package Metadata -->
    <PackageId>Errgo</PackageId>
    <Version>0.0.1</Version>
    <Authors>Diego Rönkkömäki-Tapia</Authors>
    <Description>Go-style errors-as-values error handling library for C#</Description>
    <PackageTags>error-handling;go;errors;result</PackageTags>
    <PackageProjectUrl>https://github.com/TDMR87/Ergo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TDMR87/Ergo</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    
    <!-- Include analyzers in package -->
    <IncludeBuildOutput>true</IncludeBuildOutput>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0" />
  </ItemGroup>

</Project>
