<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

  <PropertyGroup>
    <PackageId>Errgo.Analyzer</PackageId>
    <Authors>Diego Rönkkömäki-Tapia</Authors>
    <PackageProjectUrl>https://github.com/TDMR87/Errgo</PackageProjectUrl>
    <RepositoryUrl>https://github.com/TDMR87/Errgo</RepositoryUrl>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <Description>Errgo.Analyzer</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.nuget.md</PackageReadmeFile>
    <PackageIcon>errgo_logo_sm.png</PackageIcon>
    <PackageTags>errgo, analyzers, error-handling, errors, error, result, result pattern, go, gostyle, csharp, dotnet, netstandard, no-exceptions</PackageTags>
    <DevelopmentDependency>true</DevelopmentDependency>
    <NoPackageAnalysis>true</NoPackageAnalysis>

    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);_AddAnalyzersToOutput</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Errgo.Analyzer.CodeFixes\Errgo.Analyzer.CodeFixes.csproj" />
    <ProjectReference Include="..\Errgo.Analyzer\Errgo.Analyzer.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="tools\*.ps1" CopyToOutputDirectory="PreserveNewest" Pack="true" PackagePath="" />
    <None Include="README.nuget.md" Pack="true" PackagePath="\" />
    <None Include="..\..\img\errgo_logo_sm.png" Pack="true" PackagePath="\" />
    <None Include="..\..\LICENSE" Pack="true" PackagePath="\" />
  </ItemGroup>

  <Target Name="_AddAnalyzersToOutput">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(OutputPath)\Errgo.Analyzer.dll" PackagePath="analyzers/dotnet/cs" />
      <TfmSpecificPackageFile Include="$(OutputPath)\Errgo.Analyzer.CodeFixes.dll" PackagePath="analyzers/dotnet/cs" />
    </ItemGroup>
  </Target>

</Project>
